[구글 코랩(Colab)에서 실행하기](https://colab.research.google.com/github/lovedlim/tensorflow/blob/main/Part%202/2.7_reshape.ipynb)

In [ ]:
# 텐서플로 불러오기
import tensorflow as tf

# 랭크-1 텐서 정의하기
tensor = tf.constant(range(0, 24))
print(tensor)

tf.Tensor([ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23], shape=(24,), dtype=int32)


In [ ]:
tensor1 = tf.reshape(tensor, [3, 8])
print(tensor1)

tf.Tensor(
[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]], shape=(3, 8), dtype=int32)


In [ ]:
tensor2 = tf.reshape(tensor1, [-1, 4])
print(tensor2)

tf.Tensor(
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]], shape=(6, 4), dtype=int32)


In [ ]:
tensor3 = tf.reshape(tensor2, [-1])
print(tensor3)

tf.Tensor([ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23], shape=(24,), dtype=int32)


In [ ]:
tensor4 = tf.reshape(tensor3, [-1, 3, 4])
print(tensor4)

tf.Tensor(
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]], shape=(2, 3, 4), dtype=int32)


In [ ]:
tensor5 = tf.reshape(tensor4, [3, 2, 4])
print(tensor5)

tf.Tensor(
[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]]], shape=(3, 2, 4), dtype=int32)


In [ ]:
tensor6 = tf.reshape(tensor5, [3, 2, 2, 2])
print(tensor6)

tf.Tensor(
[[[[ 0  1]
   [ 2  3]]

  [[ 4  5]
   [ 6  7]]]


 [[[ 8  9]
   [10 11]]

  [[12 13]
   [14 15]]]


 [[[16 17]
   [18 19]]

  [[20 21]
   [22 23]]]], shape=(3, 2, 2, 2), dtype=int32)
