[구글 코랩(Colab)에서 실행하기](https://colab.research.google.com/github/lovedlim/tensorflow/blob/main/Part%205/5.1_rnn.ipynb)

## 임베딩

In [ ]:
# 라이브러리 불러오기
import tensorflow as tf

# 임베딩 레이어
embedding_layer = tf.keras.layers.Embedding(100, 3)
result = embedding_layer(tf.constant([12,8,15, 20])) #더미 데이터 입력
print(result)

tf.Tensor(
[[ 0.02650649 -0.03870631  0.02221387]
 [-0.01329124  0.00753369  0.02704499]
 [-0.01264749 -0.02551993  0.02355143]
 [ 0.01762089 -0.02397168 -0.00142975]], shape=(4, 3), dtype=float32)


In [ ]:
# 임베딩 레이어 활용
model = tf.keras.Sequential()
model.add(tf.keras.layers.Embedding(100, 3, input_length=32))
model.add(tf.keras.layers.LSTM(units=32))
model.add(tf.keras.layers.Dense(units=1))
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (None, 32, 3)             300       
_________________________________________________________________
lstm (LSTM)                  (None, 32)                4608      
_________________________________________________________________
dense (Dense)                (None, 1)                 33        
Total params: 4,941
Trainable params: 4,941
Non-trainable params: 0
_________________________________________________________________


In [ ]:
# 라이브러리 불러오기
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense

# 임베딩 레이어 활용
model = Sequential()
model.add(Embedding(100, 3, input_length=32))
model.add(LSTM(32))
model.add(Dense(1))
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_2 (Embedding)      (None, 32, 3)             300       
_________________________________________________________________
lstm_1 (LSTM)                (None, 32)                4608      
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 33        
Total params: 4,941
Trainable params: 4,941
Non-trainable params: 0
_________________________________________________________________


### 양방향 RNN

In [ ]:
# Bidirectional LSTM
from tensorflow.keras.layers import Bidirectional

model = Sequential()
model.add(Embedding(100,3))
model.add(Bidirectional(LSTM(32))) # 양방향 RNN
model.add(Dense(1))
model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_3 (Embedding)      (None, None, 3)           300       
_________________________________________________________________
bidirectional (Bidirectional (None, 64)                9216      
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 65        
Total params: 9,581
Trainable params: 9,581
Non-trainable params: 0
_________________________________________________________________


### 스태킹 RNN

In [ ]:
# 스태킹RNN 예제
model = Sequential()
model.add(Embedding(100,32))
model.add(LSTM(32, return_sequences=True))  # 전체 시퀀스 출력 (batch_size, timesteps, units)
model.add(LSTM(32))
model.add(Dense(1))
model.summary()

Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_4 (Embedding)      (None, None, 32)          3200      
_________________________________________________________________
lstm_3 (LSTM)                (None, None, 32)          8320      
_________________________________________________________________
lstm_4 (LSTM)                (None, 32)                8320      
_________________________________________________________________
dense_3 (Dense)              (None, 1)                 33        
Total params: 19,873
Trainable params: 19,873
Non-trainable params: 0
_________________________________________________________________


### 순환 드롭아웃

In [ ]:
# 순환 드룹아웃
model = Sequential()
model.add(Embedding(100, 32))
model.add(LSTM(32, recurrent_dropout=0.2, dropout=0.2))
model.add(Dense(1, activation='sigmoid'))
model.summary()

Model: "sequential_4"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_5 (Embedding)      (None, None, 32)          3200      
_________________________________________________________________
lstm_5 (LSTM)                (None, 32)                8320      
_________________________________________________________________
dense_4 (Dense)              (None, 1)                 33        
Total params: 11,553
Trainable params: 11,553
Non-trainable params: 0
_________________________________________________________________
